### ISSUE TITLE
The "withVertices" parameter of closestLayerSnap is not acting correctly and returns points on segments as well

### ISSUE THREAD

**Issue by fnicollet** [makinacorpus/Leaflet.GeometryUtil#25] opened 2015-02-24 17:17 UTC
Hello,

I am using the closestLayerSnap function with the withVertices parameter set to true, like:
```javascript
 var result = L.GeometryUtil.closestLayerSnap(this.map, layers, latlng, tolerance, true);
```
I would expect the snapping to only happen on vectrices that exist on the layer but instead, I also get result on segments.
I believe this is also what happened to the issue #21 and the fix (infinite tolerance or documentation fix #22 ) is not really a fix. The parameter "withVertices" should only return points that belong to the layer.

After digging a little, it is logic because of the way the code is currently implemented.
First pass is calling closestLayer:
https://github.com/makinacorpus/Leaflet.GeometryUtil/blob/master/dist/leaflet.geometryutil.js#L242

Which has no "withVertices" parameter and snap on closest, see this comment:
https://github.com/makinacorpus/Leaflet.GeometryUtil/blob/master/dist/leaflet.geometryutil.js#L211
It calls 
```javascript
ll = L.GeometryUtil.closest(map, layer, latlng);
```
without passing it the fourth parameter "withVertices" so if your position is close enough to the middle of a segment, it will return a point on this segment.
Because there is at least a result during first pass, it is then returned by closestLayerSnap 

I believe the appropriate behaviour would be to pass the withVertices parameter everywhere so that the behaviour is consistent

I'll add a PR

Thanks,
Fabien

**Comment by gutard** [comment] 2015-02-25 09:28
Duplicate of #21.

The behaviour of `closestLayerSnap` function is to get the closest point, not necessarily an existing vertex. The `with_vertex` parameter means it tries to snap to an existing vertex if possible, but fallback to a new point on a segment if it can't find an existing vertex close enough to the point. This behaviour is what we need in [Geotrek](https://github.com/makinacorpus/Geotrek). We create a new vertex if need be. Actually `with_vertex` does not mean `vertex_only`. Maybe we should rename it to something like `try_to_snap_to_existing_vertices` but this is a little bit long.

But feel free to modify your pull request to add your desired functionnality (new parameter or new function) without breaking the current behaviour.

**Comment by fnicollet** [comment] 2015-02-25 09:50
Thanks for your answer,
Even "try_to_snap_to_existing_vertices" would be misleading, because a point on a segment is not an existing vertex, it doesn't exist in the list of latlng of the object.
I think something like "snapOnSegments" would be appropriate

**Comment by mdartic** [comment] 2016-09-05 15:46
The documentation has been updated to be more easy to understand.

See the documentation method 
http://makinacorpus.github.io/Leaflet.GeometryUtil/global.html#closestLayerSnap

Hope this will help others to not lose some time to understand...

**Closed by mdartic** 2016-09-05 15:46 UTC
