### ISSUE TITLE
interpolateOnLine doesn't return correct predecessor

### ISSUE THREAD

**Issue by luiscamachopt** [makinacorpus/Leaflet.GeometryUtil#66] opened 2017-02-27 09:59 UTC
L.GeometryUtil.interpolateOnLine(myw.app.map, [L.latLng(1, 2), L.latLng(3, 4)], 0.5).predecessor
returns -1 when it should be 0

This happens when point is in first segment.

**Comment by leplatrem** [comment] 2017-03-14 12:31
Thanks for reporting!

This should be fairly to reproduce in a test case. Would you mind submitting a pull-request?

**Comment by eric7472** [comment] 2017-03-22 18:26
Hi,
It seems to be the same issue than #32.
Please find enclosed a test case. The problem is very dependent of the angle between segment.

[interpolateBug.html.zip](https://github.com/makinacorpus/Leaflet.GeometryUtil/files/862440/interpolateBug.html.zip)

**Comment by jb2b38** [comment] 2018-03-13 12:26
I have a fix for this, but I get a 403 when trying to submit a pull request.

**Comment by mdartic** [comment] 2018-03-13 12:42
Do you create a PR from a private repo ? I can't see your fork in your repositories.

**Comment by jb2b38** [comment] 2018-03-13 14:02
My bad, I cloned it to my computer from URL. PR created, thanks for pointing me in the right direction.

**Comment by mdartic** [comment] 2018-03-15 15:40
Thank you @jb2b38 for your PR.

@eric7472 @luiscamachopt could you check if the fix made by @jb2b38 fix your bug ?

Please clone https://github.com/jb2b38/Leaflet.GeometryUtil/tree/fix_66 .

**Comment by mabhub** [comment] 2018-06-22 13:13
*Just for a link to be made between issue & PR : #76*

**Closed** 2018-06-26 15:29 UTC
Labels: bug
